---
- name: Install build tooling packages
  apt: pkg={{item}} state=installed
  become: true
  with_items:
       - subversion
       - git
       - automake
       - autoconf
       - make
       - libtool
       - m4
       - zip
       - unzip
       - cmake
       - lemon
       - xz-utils
       - zlib1g-dev
  tags:
      - dev-dependencies

- name: Check if clang is already unpacked
  check_mode: False
  changed_when: False
  failed_when: False
  command: clang --version |grep -q 'clang version {{llvm.version|regex_escape()}}'
  register: clang_check

- name: Download clang+llvm
  get_url:
    url: 'http://releases.llvm.org/{{llvm.version}}/clang+llvm-{{llvm.version}}-x86_64-linux-gnu-debian8.tar.xz'
    dest: /vagrant/clang.tar.xz
    checksum: '{{llvm.checksums[llvm.version]}}'
  when: clang_check.rc != 0
  tags:
    - clang

- name: Unpack clang+llvm
  unarchive:
    remote_src: true
    src: '/vagrant/clang.tar.xz'
    dest: /usr/local
    extra_opts:
      - '--strip-components=1'
    creates: /usr/local/bin/clang
  when: clang_check.rc != 0
  become: true
  tags:
      - clang

- name: Set clang as the default C compiler
  become: true
  alternatives: name=cc path=/usr/local/bin/clang
  tags:
      - clang

- name: Set clang++ as the default C++ compiler
  become: true
  alternatives: name=c++ path=/usr/local/bin/clang++
  tags:
      - clang
