---
- name: Install build tooling packages
  apt: pkg={{item}} state=installed
  become: true
  with_items:
       - subversion
       - git
       - automake
       - autoconf
       - make
       - libtool
       - m4
       - zip
       - unzip
       - cmake
       - clang
       - lemon
       - zlib1g-dev
  tags:
      - dev-dependencies

- name: Install ninja build tool
  apt: pkg=ninja-build state=installed
  become: true
  when: llvm.generator == 'Ninja'
  tags:
      - dev-dependencies
      - clang

- name: Register make as the LLVM build tool fact
  set_fact:
    llvm_buildtool: make
  when: llvm.generator != 'Ninja'
  tags:
      - clang

- name: Register ninja as the LLVM build tool fact
  set_fact:
    llvm_buildtool: ninja
  when: llvm.generator == 'Ninja'
  tags:
      - clang

- name: Checkout LLVM
  subversion: repo={{ llvm.llvm_repo }} dest={{ llvm.src_dir }}
  register: llvm_checkout
  tags:
      - clang

- name: Checkout clang
  subversion: repo={{ llvm.clang_repo }} dest={{ llvm.src_dir }}/tools/clang
  register: clang_checkout
  tags:
      - clang

- name: Create llvm build directory
  file: path={{ llvm.build_dir }} state=directory
  tags:
      - clang

- name: Generate build files
  command: cmake -G "{{ llvm.generator }}" -DCMAKE_BUILD_TYPE={{ llvm.build_type }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_TARGETS_TO_BUILD={{ llvm.targets }} {{ llvm.src_dir }} chdir={{ llvm.build_dir }}
  when: llvm_checkout.changed or clang_checkout.changed
  tags:
      - clang

- name: Build LLVM/clang
  command: "{{ llvm_buildtool }} chdir={{ llvm.build_dir }}"
  when: llvm_checkout.changed or clang_checkout.changed
  tags:
      - clang
- name: Remove packaged clang
  apt: pkg={{item}} state=absent
  become: true
  with_items:
       - clang
       - libobjc-4.9-dev
       - libobjc4
  tags:
      - dev-dependencies

- name: Install LLVM/clang
  command: "{{ llvm_buildtool }} install chdir={{ llvm.build_dir }}"
  become: true
  when: llvm_checkout.changed or clang_checkout.changed
  tags:
      - clang

- name: Set clang as the default C compiler
  become: true
  alternatives: name=cc path=/usr/local/bin/clang
  tags:
      - clang

- name: Set clang++ as the default C++ compiler
  become: true
  alternatives: name=c++ path=/usr/local/bin/clang++
  tags:
      - clang
