---
- name: Configure gnustep-make
  command: ./configure --with-library-combo=ng-gnu-gnu --enable-objc-nonfragile-abi CC=cc CXX=c++
  args: 
    chdir: "{{ gnustep.make.src_dir }}"
- name: Install gnustep-make
  become: true
  command: make install 
  args:
    chdir: "{{ gnustep.make.src_dir }}"
- name: Add GNUstep environment to profile.d
  become: true
  template: src=halbordnung.de-objc_dev-gnustep_make.sh.j2 dest=/etc/profile.d/halbordnung.de-objc_dev-gnustep-_make.sh owner=root group=root mode=0644
